### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by panikajo** [Toiongo/VK_Audio_Download_Ext#1]
extnesion not working

**Comment by Toiongo** [comment]
I've updated some files, pls check again and see if js console outputs "No files for this track are present."; If that's the case - you need to search for a different upload of the same track, preferably one with album art - those work most of the time. Not all tracks can be downloaded with the extension at the moment, sadly.

**Comment by Toiongo** [comment]
Also you might need to start playing the track you wish to download.
